// Barrel module - backward-compatible apiService object + re-exports
// Domain logic lives in individual modules (authApi, clientApi, etc.)

import { setToken, getToken, clearToken, isAuthenticated } from './apiClient';
import * as auth from './authApi';
import * as users from './userApi';
import * as clients from './clientApi';
import * as licenses from './licenseApi';
import * as importGroups from './importGroupApi';
import * as payments from './paymentApi';
import * as weapons from './weaponApi';
import * as documents from './documentApi';
import * as config from './configApi';
import * as catalogs from './catalogApi';
import * as contracts from './contractApi';

// Re-export all types
export type {
  ApiResponse, Page, LoginRequest, LoginResponse, User, Client, Pago, PlanPago,
  GrupoImportacion, SaldoCliente, Licencia, LicenciaCreateRequest, LicenciaSearchParams,
  Weapon, WeaponCategory, License, Role, ClientType, ImportType, IdentificationType,
  Question, DocumentType, ClientImportType, SystemConfig, TipoProceso,
} from './types';

// Backward-compatible apiService object
export const apiService = {
  // Token management
  setToken,
  getToken,
  clearToken,
  isAuthenticated,

  // Auth
  login: auth.login,
  logout: auth.logout,
  refreshToken: auth.refreshToken,
  getCurrentUser: auth.getCurrentUser,
  getMe: auth.getMe,
  getUserRoles: auth.getUserRolesFromAuth,
  hasRole: auth.hasRole,
  hasAnyRole: auth.hasAnyRole,

  // Users
  getUsers: users.getUsers,
  getUser: users.getUser,
  createUser: users.createUser,
  updateUser: users.updateUser,
  deleteUser: users.deleteUser,
  getVendedores: users.getVendedores,
  getUserRolesByUserId: users.getUserRolesByUserId,
  assignRoles: users.assignRoles,
  removeUserRole: users.removeUserRole,

  // Clients
  getClientes: clients.getClientes,
  getMisClientes: clients.getMisClientes,
  getTiposCliente: clients.getTiposCliente,
  getTiposIdentificacion: clients.getTiposIdentificacion,
  getProvincias: clients.getProvincias,
  getProvinciasCompletas: clients.getProvinciasCompletas,
  getCantones: clients.getCantones,
  getCliente: clients.getCliente,
  getClienteById: clients.getClienteById,
  createCliente: clients.createCliente,
  buscarOCrearClienteFantasmaVendedor: clients.buscarOCrearClienteFantasmaVendedor,
  updateCliente: clients.updateCliente,
  patchCliente: clients.patchCliente,
  validarDatosPersonales: clients.validarDatosPersonales,
  verifyEmailToken: clients.verifyEmailToken,
  getTokenInfo: clients.getTokenInfo,
  deleteCliente: clients.deleteCliente,
  getClientesPorVendedor: clients.getClientesPorVendedor,
  buscarClientePorIdentificacion: clients.buscarClientePorIdentificacion,
  validarIdentificacion: clients.validarIdentificacion,
  cambiarEstadoCliente: clients.cambiarEstadoCliente,
  getTodosClientes: clients.getTodosClientes,
  getDashboardJefeVentas: clients.getDashboardJefeVentas,
  getClientesDeHoy: clients.getClientesDeHoy,
  getClientesPendientesContrato: clients.getClientesPendientesContrato,
  getClientesDisponibles: clients.getClientesDisponibles,
  cambiarEstadoDesistimiento: clients.cambiarEstadoDesistimiento,
  getFormularioCliente: clients.getFormularioCliente,
  getFormularioClienteConEstadoMilitar: clients.getFormularioClienteConEstadoMilitar,
  getTiposClienteConfig: clients.getTiposClienteConfig,

  // Licenses
  getLicencias: licenses.getLicencias,
  getLicencia: licenses.getLicencia,
  createLicencia: licenses.createLicencia,
  updateLicencia: licenses.updateLicencia,
  deleteLicencia: licenses.deleteLicencia,
  getLicenciasActivas: licenses.getLicenciasActivas,
  getLicenciasDisponibles: licenses.getLicenciasDisponibles,
  getLicenciasProximasAVencer: licenses.getLicenciasProximasAVencer,
  buscarLicencias: licenses.buscarLicencias,
  getEstadisticasLicencias: licenses.getEstadisticasLicencias,
  cambiarEstadoLicencia: licenses.cambiarEstadoLicencia,
  getLicenses: licenses.getLicenses,
  getLicenseById: licenses.getLicenseById,
  createLicense: licenses.createLicense,
  updateLicense: licenses.updateLicense,
  deleteLicense: licenses.deleteLicense,

  // Import Groups
  getGruposImportacion: importGroups.getGruposImportacion,
  getGrupoImportacion: importGroups.getGrupoImportacion,
  getProcesosGrupoImportacion: importGroups.getProcesosGrupoImportacion,
  actualizarProcesosGrupoImportacion: importGroups.actualizarProcesosGrupoImportacion,
  getAlertasProcesosImportacion: importGroups.getAlertasProcesosImportacion,
  createGrupoImportacion: importGroups.createGrupoImportacion,
  crearGrupoImportacion: importGroups.crearGrupoImportacion,
  actualizarGrupoImportacion: importGroups.actualizarGrupoImportacion,
  getVendedoresParaGrupo: importGroups.getVendedoresParaGrupo,
  getCategoriasArmasParaGrupo: importGroups.getCategoriasArmasParaGrupo,
  updateGrupoImportacion: importGroups.updateGrupoImportacion,
  getGruposActivos: importGroups.getGruposActivos,
  agregarClienteAGrupo: importGroups.agregarClienteAGrupo,
  getClientesDelGrupo: importGroups.getClientesDelGrupo,
  verificarGrupoDisponiblePorTipo: importGroups.verificarGrupoDisponiblePorTipo,
  removerClienteDelGrupo: importGroups.removerClienteDelGrupo,
  configurarCupo: importGroups.configurarCupo,
  getGruposParaOperaciones: importGroups.getGruposParaOperaciones,
  getGrupoResumen: importGroups.getGrupoResumen,
  definirPedido: importGroups.definirPedido,
  puedeDefinirPedido: importGroups.puedeDefinirPedido,
  getResumenGrupo: importGroups.getResumenGrupo,
  getGruposParaGestionImportaciones: importGroups.getGruposParaGestionImportaciones,
  notificarAgenteAduanero: importGroups.notificarAgenteAduanero,
  getGruposParaJefeVentas: importGroups.getGruposParaJefeVentas,
  cargarDocumentoGrupo: importGroups.cargarDocumentoGrupo,
  getDocumentosGrupo: importGroups.getDocumentosGrupo,
  eliminarDocumentoGrupo: importGroups.eliminarDocumentoGrupo,
  notificarPagoFabrica: importGroups.notificarPagoFabrica,
  puedeNotificarPago: importGroups.puedeNotificarPago,
  registrarFechaLlegada: importGroups.registrarFechaLlegada,
  registrarNumeroPrevia: importGroups.registrarNumeroPrevia,

  // Payments
  getPagos: payments.getPagos,
  getPago: payments.getPago,
  createPago: payments.createPago,
  getPagosPorCliente: payments.getPagosPorCliente,
  getSaldoCliente: payments.getSaldoCliente,
  getCuotasPorPago: payments.getCuotasPorPago,
  pagarCuota: payments.pagarCuota,
  crearCuotaPago: payments.crearCuotaPago,
  generarRecibo: payments.generarRecibo,
  descargarRecibo: payments.descargarRecibo,
  enviarReciboPorCorreo: payments.enviarReciboPorCorreo,
  crearPago: payments.crearPago,
  getPagosCliente: payments.getPagosCliente,

  // Weapons
  getArmas: weapons.getArmas,
  getArmaById: weapons.getArmaById,
  createArma: weapons.createArma,
  createArmaWithImage: weapons.createArmaWithImage,
  updateArma: weapons.updateArma,
  updateArmaWithImage: weapons.updateArmaWithImage,
  deleteArma: weapons.deleteArma,
  getArmasByCategoria: weapons.getArmasByCategoria,
  getArmasDisponibles: weapons.getArmasDisponibles,
  getCategoriasArma: weapons.getCategoriasArma,
  getWeaponCategories: weapons.getWeaponCategories,
  getWeaponCategoryById: weapons.getWeaponCategoryById,
  createWeaponCategory: weapons.createWeaponCategory,
  updateWeaponCategory: weapons.updateWeaponCategory,
  deleteWeaponCategory: weapons.deleteWeaponCategory,
  getArmasConStock: weapons.getArmasConStock,
  getStockArma: weapons.getStockArma,
  verificarStock: weapons.verificarStock,
  getStockTodasArmas: weapons.getStockTodasArmas,
  crearReservaArma: weapons.crearReservaArma,
  getArmasCliente: weapons.getArmasCliente,
  actualizarArmaReserva: weapons.actualizarArmaReserva,
  getArmasEnStockVendedor: weapons.getArmasEnStockVendedor,
  reasignarArmaACliente: weapons.reasignarArmaACliente,
  getArmasReasignadas: weapons.getArmasReasignadas,
  asignarNumeroSerie: weapons.asignarNumeroSerie,
  getReservasPendientes: weapons.getReservasPendientes,
  getReservasPendientesAsignacion: weapons.getReservasPendientesAsignacion,
  getSeriesDisponibles: weapons.getSeriesDisponibles,
  asignarSerie: weapons.asignarSerie,

  // Documents
  cargarDocumentoCliente: documents.cargarDocumentoCliente,
  getDocumentosCliente: documents.getDocumentosCliente,
  getDocumentoCliente: documents.getDocumentoCliente,
  actualizarDocumentoCliente: documents.actualizarDocumentoCliente,
  eliminarDocumentoCliente: documents.eliminarDocumentoCliente,
  cambiarEstadoDocumento: documents.cambiarEstadoDocumento,
  verificarDocumentosCompletos: documents.verificarDocumentosCompletos,
  getResumenDocumentos: documents.getResumenDocumentos,
  guardarRespuestaCliente: documents.guardarRespuestaCliente,
  getRespuestasCliente: documents.getRespuestasCliente,
  verificarProcesoCliente: documents.verificarProcesoCliente,
  completarProcesoCliente: documents.completarProcesoCliente,
  confirmarInicioProceso: documents.confirmarInicioProceso,
  getElementosFaltantes: documents.getElementosFaltantes,
  getEstadoProceso: documents.getEstadoProceso,

  // Config
  getConfiguracion: config.getConfiguracion,
  getValorConfiguracion: config.getValorConfiguracion,
  getConfiguracionCompleta: config.getConfiguracionCompleta,
  getConfiguracionSistema: config.getConfiguracionSistema,
  getPreguntas: config.getPreguntas,
  getPreguntaById: config.getPreguntaById,
  getPreguntasCliente: config.getPreguntasCliente,
  createPregunta: config.createPregunta,
  updatePregunta: config.updatePregunta,
  deletePregunta: config.deletePregunta,
  getTiposDocumento: config.getTiposDocumento,
  getTiposDocumentoGruposImportacion: config.getTiposDocumentoGruposImportacion,
  getTipoDocumentoById: config.getTipoDocumentoById,
  getDocumentosRequeridos: config.getDocumentosRequeridos,
  createTipoDocumento: config.createTipoDocumento,
  updateTipoDocumento: config.updateTipoDocumento,
  deleteTipoDocumento: config.deleteTipoDocumento,
  getTiposProceso: config.getTiposProceso,
  getTipoProcesoById: config.getTipoProcesoById,

  // Catalogs
  getClientTypes: catalogs.getClientTypes,
  getClientTypeById: catalogs.getClientTypeById,
  createClientType: catalogs.createClientType,
  updateClientType: catalogs.updateClientType,
  deleteClientType: catalogs.deleteClientType,
  getIdentificationTypes: catalogs.getIdentificationTypes,
  getIdentificationTypeById: catalogs.getIdentificationTypeById,
  createIdentificationType: catalogs.createIdentificationType,
  updateIdentificationType: catalogs.updateIdentificationType,
  deleteIdentificationType: catalogs.deleteIdentificationType,
  getImportTypes: catalogs.getImportTypes,
  getImportTypeById: catalogs.getImportTypeById,
  createImportType: catalogs.createImportType,
  updateImportType: catalogs.updateImportType,
  deleteImportType: catalogs.deleteImportType,
  getTipoClienteImportacion: catalogs.getTipoClienteImportacion,
  getTipoClienteImportacionById: catalogs.getTipoClienteImportacionById,
  getTipoClienteImportacionByTipoCliente: catalogs.getTipoClienteImportacionByTipoCliente,
  createTipoClienteImportacion: catalogs.createTipoClienteImportacion,
  deleteTipoClienteImportacion: catalogs.deleteTipoClienteImportacion,
  getRoles: catalogs.getRoles,
  getRoleById: catalogs.getRoleById,
  createRole: catalogs.createRole,
  updateRole: catalogs.updateRole,
  deleteRole: catalogs.deleteRole,

  // Contracts
  generarYEnviarContrato: contracts.generarYEnviarContrato,
  obtenerContratosPorCliente: contracts.obtenerContratosPorCliente,
  obtenerDatosContrato: contracts.obtenerDatosContrato,
  generarContrato: contracts.generarContrato,
  cargarContratoFirmado: contracts.cargarContratoFirmado,
  getContratosCliente: contracts.getContratosCliente,
  generarAutorizacion: contracts.generarAutorizacion,
  getAutorizacionesPorCliente: contracts.getAutorizacionesPorCliente,
};

export default apiService;
