spring.datasource.url=jdbc:postgresql://72.167.52.14:5432/devdb
spring.datasource.username=devuser
spring.datasource.password=devpass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
