spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/armas_importacion_dev
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

app:
  frontend-url: http://localhost:3000