spring:
  datasource:
    url: jdbc:postgresql://db:5432/armas_importacion_prod
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

app:
  frontend-url: ${FRONTEND_URL:https://tudominio.com}